'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Search, SlidersHorizontal, ShoppingBag } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetTrigger, SheetContent, SheetTitle } from '@/components/ui/sheet';
import { Slider } from '@/components/ui/slider';
import { Product, priceOf, currency } from '@/lib/catalog';
import { ProductCard } from './storefront';
export function Choice({ value, onChange, options, label }: {
    value: string;
    onChange: (s: string) => void;
    options: string[];
    label: string;
}) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>; }
export default function CatalogBrowser({ products, categories, initialCategory = '', initialBrand = '' }: {
    products: Product[];
    categories: any[];
    initialCategory?: string;
    initialBrand?: string;
}) {
    const [q, setQ] = useState(''), [selectedCategories, setCategories] = useState<string[]>(initialCategory ? [initialCategory] : []), [brands, setBrands] = useState<string[]>(initialBrand ? [initialBrand] : []), [types, setTypes] = useState<string[]>([]), [availability, setAvailability] = useState<string[]>([]), [featured, setFeatured] = useState(false), [sort, setSort] = useState('Recommended'), [suggest, setSuggest] = useState(false), [open, setOpen] = useState(false);
    const maximum = Math.max(100000, ...products.map(p => priceOf(p) || 0));
    const [price, setPrice] = useState([0, maximum]), [priceKnown, setPriceKnown] = useState(false);
    useEffect(() => { const params = new URLSearchParams(location.search); setQ(params.get('q') || ''); if (params.has('search'))
        document.getElementById('product-search')?.focus(); }, []);
    const matches = (p: Product) => [p.name, p.brand, p.sku, p.type, p.shortDescription, p.category, ...p.tags, categories.find(c => c.slug === p.category)?.name].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase().trim());
    const results = useMemo(() => { const r = products.filter(p => matches(p) && (!selectedCategories.length || selectedCategories.includes(p.category)) && (!brands.length || brands.some(b=>p.brand===b||p.brand.split("/").map(s=>s.trim()).includes(b))) && (!types.length || types.includes(p.type)) && (!availability.length || availability.includes(p.availability)) && (!featured || p.featured) && (!priceKnown || priceOf(p) !== null) && (priceOf(p) === null || priceOf(p)! >= price[0] && priceOf(p)! <= price[1])); return r.sort((a, b) => sort === 'A–Z' ? a.name.localeCompare(b.name) : sort === 'Price low to high' ? (priceOf(a) ?? Infinity) - (priceOf(b) ?? Infinity) : sort === 'Price high to low' ? (priceOf(b) ?? -Infinity) - (priceOf(a) ?? -Infinity) : sort === 'Newest' ? b.createdAt.localeCompare(a.createdAt) : Number(b.featured) - Number(a.featured)); }, [products, q, selectedCategories, brands, types, availability, featured, sort, price, priceKnown]);
    const toggle = (value: string, values: string[], setter: (v: string[]) => void) => setter(values.includes(value) ? values.filter(v => v !== value) : [...values, value]);
    const clear = () => { setQ(''); setCategories([]); setBrands([]); setTypes([]); setAvailability([]); setFeatured(false); setPrice([0, maximum]); setPriceKnown(false); };
    useEffect(() => { const context = (document as any).modelContext; if (!context?.registerTool)
        return; const lifecycle = new AbortController(); void Promise.resolve(context.registerTool({ name: 'search_medical_products', description: 'Search the visible catalogue by product, category, brand or SKU.', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: (input: any) => { if (typeof input?.query !== 'string' || input.query.length > 200)
            throw new Error('Invalid search query'); setQ(input.query); return { products: products.filter(p => [p.name, p.brand, p.category, p.sku, ...p.tags].join(' ').toLowerCase().includes(input.query.toLowerCase())).map(p => ({ id: p.id, name: p.name, price: priceOf(p) })) }; } }, { signal: lifecycle.signal })).catch(() => { }); return () => lifecycle.abort(); }, [products]);
    const filters = <div className="filter-panel"><h2>Filter products</h2><button className="text-link" onClick={clear}>Clear all filters</button><div className="filter-group"><h3>Category</h3>{categories.map(c => <label key={c.slug} className="filter-option"><Checkbox checked={selectedCategories.includes(c.slug)} onCheckedChange={() => toggle(c.slug, selectedCategories, setCategories)}/>{c.name}</label>)}</div><div className="filter-group"><h3>Brand</h3>{[...new Set(products.map(p => p.brand))].map(b => <label key={b} className="filter-option"><Checkbox checked={brands.includes(b)} onCheckedChange={() => toggle(b, brands, setBrands)}/>{b}</label>)}</div><div className="filter-group"><h3>Price (NPR)</h3><Slider min={0} max={maximum} step={500} value={price} onValueChange={setPrice} aria-label="Price range"/><p style={{ fontSize: 12, marginTop: 15 }}>{currency(price[0])} – {currency(price[1])}</p><label className="filter-option"><Checkbox checked={priceKnown} onCheckedChange={v => setPriceKnown(!!v)}/>Show priced products only</label><small>Quote-only products remain visible unless excluded.</small></div><div className="filter-group"><h3>Availability</h3>{['Contact for availability', 'In stock', 'Out of stock', 'On request'].map(v => <label className="filter-option" key={v}><Checkbox checked={availability.includes(v)} onCheckedChange={() => toggle(v, availability, setAvailability)}/>{v}</label>)}</div><div className="filter-group"><h3>Product type</h3>{[...new Set(products.map(p => p.type))].map(v => <label className="filter-option" key={v}><Checkbox checked={types.includes(v)} onCheckedChange={() => toggle(v, types, setTypes)}/>{v}</label>)}</div><label className="filter-option"><Checkbox checked={featured} onCheckedChange={v => setFeatured(!!v)}/>Featured products</label></div>;
    return <div className="catalog-layout"><aside className="panel filter-desktop" style={{ padding: 0 }}>{filters}</aside><div><Link className="text-link" style={{ marginBottom: 18 }} href="/accessories">Browse accessories</Link><div className="catalog-toolbar"><div className="search-box"><input id="product-search" className="search-input" placeholder="Search equipment, brands, SKU…" aria-label="Search products" value={q} onChange={e => { setQ(e.target.value); setSuggest(true); }} onFocus={() => setSuggest(true)} onBlur={() => setTimeout(() => setSuggest(false), 150)}/>{q && suggest && <div className="search-suggestions" aria-label="Search suggestions">{products.filter(matches).slice(0, 5).map(p => <Link key={p.id} href={'/products/' + p.slug}>{p.name} <small>· {p.brand}</small></Link>)}</div>}</div><Choice label="Sort products" value={sort} onChange={setSort} options={['Recommended', 'Newest', 'Price low to high', 'Price high to low', 'A–Z']}/><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="btn outline filter-mobile"><SlidersHorizontal size={17}/> Filters</button></SheetTrigger><SheetContent style={{ overflowY: 'auto' }}><SheetTitle>Product filters</SheetTitle>{filters}<button className="btn" onClick={() => setOpen(false)}>Show results</button></SheetContent></Sheet></div><p aria-live="polite" style={{ fontSize: 14 }}>{results.length} product{results.length === 1 ? '' : 's'}</p>{results.some(p => !p.published) && <p className="notice">Private preview: these product records await supply verification. Orders placed here are review requests, subject to confirmation.</p>}{results.length ? <div className="product-grid">{results.map(p => <ProductCard key={p.id} product={p}/>)}</div> : <div className="empty-state panel"><Search size={42}/><h2>No products found</h2><p>Try changing your search or filter. Our team can also help with your equipment needs.</p><button className="btn outline" onClick={clear}>Reset filters</button> <Link className="btn" href="/request-quote">Request a Quote</Link></div>}</div></div>;
}
